language: python
install: pip install virtualenv --upgrade
script: make
after_success: make push
branches:
    except:
        - master
env:
    global:
        # GH_TOKEN
        - secure: "YXgJlui6OJjTEDNBVW82I+/NF5ry5WC4QLAu2D2iNOtAq0tbZe2gSd/n6JCqfYgXsTlIgnVrN1qdH8582IXHFmZH2bUhRJ+skOgn9Y0vTmhz1Kl29BAzN6v0U0ikz5htAyzISr7s+MM78ShHMzzA/mnmkgVFhYXqUTwsB3/iE9Q="
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
